version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - area:core
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5
