package rules

import (
	"path/filepath"

	"github.com/Ozark-Security-Labs/PkgWarden/internal/model"
)

type missingLockfileRule struct{}

func (missingLockfileRule) Metadata() model.Rule {
	return model.Rule{
		ID:          "PW-R001",
		Ecosystem:   "multi",
		Category:    "lockfile",
		Severity:    model.SeverityMedium,
		Profiles:    []model.ProfileID{model.ProfileBaseline, model.ProfileStrict},
		Remediation: "Commit the package-manager lockfile for each manifest where the ecosystem supports lockfiles.",
		References:  []model.Reference{},
	}
}

func (missingLockfileRule) Evaluate(ctx Context) []model.Finding {
	findings := []model.Finding{}
	for _, manifest := range ctx.Inventory.Manifests {
		if len(manifest.Locations) == 0 {
			continue
		}
		expected, ok := expectedLockfiles(manifest)
		if !ok {
			continue
		}
		manifestPath := manifest.Locations[0].Path
		if hasSameDirectoryLockfile(ctx.Inventory.Lockfiles, manifestPath, expected) {
			continue
		}
		location := manifest.Locations[0]
		findings = append(findings, model.Finding{
			ID:         "PW-R001:" + manifestPath,
			RuleID:     "PW-R001",
			Title:      "Package manifest has no matching lockfile",
			Severity:   model.SeverityMedium,
			Category:   "lockfile",
			Confidence: model.ConfidenceHigh,
			Locations:  []model.Location{location},
			Evidence: []model.Evidence{
				{
					Description: "Manifest " + manifestPath + " was detected without a same-directory lockfile.",
					Locations:   []model.Location{location},
				},
			},
			Recommendation: "Commit a same-directory lockfile generated by " + manifest.PackageManager + ".",
			References:     []model.Reference{},
			Autofix:        model.Autofix{Available: false},
		})
	}
	return findings
}

func expectedLockfiles(manifest model.InventoryItem) ([]string, bool) {
	switch manifest.Name {
	case "package.json":
		return []string{"package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml"}, true
	case "go.mod":
		return []string{"go.sum"}, true
	case "pyproject.toml":
		return []string{"poetry.lock", "uv.lock"}, true
	case "Pipfile":
		return []string{"Pipfile.lock"}, true
	case "Cargo.toml":
		return []string{"Cargo.lock"}, true
	case "Gemfile":
		return []string{"Gemfile.lock"}, true
	case "composer.json":
		return []string{"composer.lock"}, true
	default:
		return nil, false
	}
}

func hasSameDirectoryLockfile(lockfiles []model.InventoryItem, manifestPath string, expected []string) bool {
	dir := filepath.ToSlash(filepath.Dir(manifestPath))
	if dir == "." {
		dir = ""
	}
	expectedSet := map[string]struct{}{}
	for _, name := range expected {
		expectedSet[name] = struct{}{}
	}
	for _, lockfile := range lockfiles {
		if len(lockfile.Locations) == 0 {
			continue
		}
		path := lockfile.Locations[0].Path
		lockDir := filepath.ToSlash(filepath.Dir(path))
		if lockDir == "." {
			lockDir = ""
		}
		if lockDir != dir {
			continue
		}
		if _, ok := expectedSet[lockfile.Name]; ok {
			return true
		}
	}
	return false
}
